[workspace]
resolver = "2"
members = ["circle", "coordinates", "cursor", "input", "mouse", "movement", "mutability", "positions", "percentages", "fractions", "absolute", "relative", "tap", "condition", "shift", "distance", "radar", "direction", "line", "vector", "chase", "stop", "segment", "turret", "functions", "random", "for-loop", "any-count", "list", "colors", "structs", "drag-radius", "draw-order", "rectangle", "buttons", "rect-buttons", "turret-volley", "circles-vanish", "turret-bounds", "turret-cleanup", "lerp", "smooth-chase", "orbit", "steering", "polygons", "arrows", "arc", "detection-sector", "detection-zone", "index-trap", "text-on-screen", "circle-id", "hashmap", "circle-intersection", "screen-center", "auto-increment"]
